### ISSUE TITLE
Why isn't MY_SECRET_TOKEN an env var?

### ISSUE THREAD

**Issue by drusellers** [jpkha/nextjs13-storyblok#2]
https://github.com/jpkha/nextjs13-storyblok/blob/main/pages/api/preview.js#L8

```js
  if (req.query.secret !== 'MY_SECRET_TOKEN') {
    return res.status(401).json({ message: 'Invalid token' })
  }
```

When discussing the preview setup, I'm curious why the secret isn't set up and demoed as an ENV VAR as well. Like the `NEXT_PUBLIC_STORYBLOK_VERSION` is at https://github.com/jpkha/nextjs13-storyblok/blob/main/app/%5B...slug%5D/page.tsx#L40

```
    const isPreviewMode = !!data && data.key === 'MY_SECRET_TOKEN';
    const version = process.env.NEXT_PUBLIC_STORYBLOK_VERSION;
```

**Comment by jpkha** [comment]
@drusellers you are right, I could make a env var for 'MY_SECRET_TOKEN'. It's just an example for enabling the preview mode with Nextjs.

**Comment by jpkha** [comment]
I change `MY_SECRET_TOKEN` for an environment variable as you suggest. Thank you
