### ISSUE TITLE
previewData() is undefined

### ISSUE THREAD

**Issue by kb1995** [jpkha/nextjs13-storyblok#3]
I tried implementing your implementation for previews, but when I tried it, I get previewData() from 'next/headers' being undefined. I'm on 13.4 - do you get the same?

**Comment by jpkha** [comment]
@kb1995  yes I got the same. They change `previewDate()`to `draftMode`.
https://nextjs.org/docs/app/building-your-application/configuring/draft-mode

**Comment by jpkha** [comment]
@kb1995  Can you try my latest version ? it should be fine now
